<?php

/**
 * @file
 * Contains \Drupal\ipu_layouts\Plugin\Layout\IpuLayoutClass
 */

/**
 * @file
 * Contains \Drupal\ipu_layouts\Plugin\Layout\MyLayoutClass
 */

namespace Drupal\ipu_layouts\Plugin\Layout;

use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\StringTranslation;
use Drupal\Core\Layout\LayoutDefault;
use Drupal\node\NodeInterface;

class IpuLayoutClass extends LayoutDefault {

  //use StringTranslationTrait;

  /**
   * {@inheritdoc}
   */
  public function defaultConfiguration() {
    return parent::defaultConfiguration() + [
        'extra_classes' => 'Default',
      ];
  }

  /**
   * {@inheritdoc}
   */
  public function buildConfigurationForm(array $form, FormStateInterface $form_state) {
    $configuration = $this->getConfiguration();
    $form['extra_classes'] = [
      '#type' => 'textfield',
      '#title' => $this->t('Extra classes'),
      '#default_value' => $configuration['extra_classes'],
    ];
    return $form;
  }

  /**
   * @inheritDoc
   */
  public function submitConfigurationForm(array &$form, FormStateInterface $form_state) {
    parent::submitConfigurationForm($form, $form_state);

    $this->configuration['extra_classes'] = $form_state->getValue('extra_classes');
  }

  function ipu_layouts_theme() {
    return [
      'ipu-country-2col-stacked' => [
        'template' => 'templates/ipu-country-2col-stacked',
        // layout_plugin expects the theme hook to be declared with this:
        'render element' => 'content',
      ],
    ];
  }
}
