# The services of the project.
#
# Each service listed will be deployed
# to power your Platform.sh project.

mysqldb:
    type: mysql:10.2
    disk: 3000

rediscache:
    type: redis:5.0

#solrsearch:
#    type: solr:7.7
#    disk: 1024
#    configuration:
#        cores:
#            maincore:
#                conf_dir: !archive "solr-conf/7.x"
#        endpoints:
#            main:
#                core: maincore
